matrix:
  include:
    - language: node_js
      node_js: '12'
      python: '3.7'
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "IjWgCHYbNVH+LJeuuzms7hu4u5aWL/Z69WrQpaF8BdLoyBjryMELQqFP0sI2C/R5CKRUhX++pZMWi/K3Ox4ZdIWIRdzqdE3Xi86rakZb8jUo/r8F9fLUNtq+fQVue1ingepp0tgB352Fq9b3ibrdENLF9wAW2PV6CL8mVJEhPWU4j65zIlyex6Nz+WT4+6T9dV8Mh8RJV9biBprEHNMoJVc3VJO+sN7sC04tLE5CNrUDpvdKJrTHe4Ns9UH5U/INle4D7TopBEei0oAuyM4RxpeMhEMalMw08GVzigWXlajyrFTfgQAqnUdtO57FWLVa2FeM6hEMGPz0GFNkoOnxSJVOmIscsgvJuxJ5Grlr2cY0rqyXzM6PKQjUVmY/FKvUGqFDBweI2R07wfOi1GR6VDtZduQsO7MbkEQa5kkx5C6VuJq4FkCALmOo0HWLqzcAbAEUfbWqDHTY36k9UwoXaJLsPxDHfzVYoXyQ7luvTzNg3P6YM2rWzbbT+3chkkZFD7U68EYiVm1QP0sFRC/LFINnjjcCDdPV/43ENEAViDmX9C1XPVKjdYnuPnrDXsjX+oyFEjtCRxGGlPP0Q/wbe1UET8LuDtDgbQJKu6dX0bYRgD0XHxf4ss1nQOf15pR6CoazTNsMcJw2pHLEpftRsBPLqa3P00px1vW746PFIN8="
      cache:
        - yarn: true
        - pip: true
      ignore:
        - ./src/serviceWorker.js
      install:
        - cd frontend
        - yarn install
        - yarn global add coveralls
        - gem install coveralls-lcov
        - cd ../
        - cd backend
        - source ~/virtualenv/python3.7/bin/activate
        - pip install -r requirements.txt --progress-bar off
        - pip install --progress-bar off coveralls
        - cd ../
      script:
        - cd frontend
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - cd ..
        - cd backend
        - pylint **/*.py --load-plugins pylint_django
        - python manage.py migrate  
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd ../
        - sonar-scanner
        - cd frontend
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ..
        - cd backend
        - coveralls --merge=../frontend/coverage.json
        - cd ../

    - language: node_js
      node_js: '12'
      cache:
        - yarn: true
      before_install:
        - cd frontend
      install:
        - yarn install
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false

    - language: python
      python: '3.7'
      cache:
        - pip: true
      before_install:
        - cd backend
      install:
        - pip install --progress-bar off -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='fontopia/views' --omit 'fontopia/tests/*,*__init__.py,fontopia/migrations/*' manage.py test
        - coverage xml
      after_success:
        - bash <(curl -s https://codecov.io/bash)
