# Generated by Django 3.1.2 on 2020-12-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fontopia', '0002_auto_20201108_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='selected_font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fontopia.font'),
        ),
    ]
