# Generated by Django 3.1.2 on 2020-12-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fontopia', '0003_auto_20201210_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contents',
            new_name='content',
        ),
    ]
